[package]
name = "futures-tokio-compat"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies]
futures-core = "0.3"
futures-io = "0.3"
tokio-io = "0.2.0-alpha.6"
tokio-executor = "0.2.0-alpha.6"
log = "0.4.8"
pin-project = "0.4.5"
